import = [
  # "~/.config/alacritty/themes/catppuccin_mocha.toml"
  "~/.config/alacritty/themes/catppuccin_macchiato.toml"
  #"~/.config/alacritty/themes/gruvbox-material.yml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.dimensions]
columns = 80
lines = 30

[window.padding]
x = 25
y = 20


[scrolling]
history = 100000
multiplier = 4

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
