if has("gui_running")
  " Set a custom font installled
  set guifont=Fira\ Mono\ for\ Powerline:h14
  set guifontwide=Hack\ Nerd\ Font:h14
  set guioptions=r
  set linespace=2
  highlight EndOfBuffer gui=NONE guifg=bg guibg=bg

  " Display more of the file by default
  " Hide the toolbar.
  "set guioptions-=T

  " Hide the left-scroll bar.
  "set guioptions-=L
  " HIde the left-scroll bar
  "set guioptions-=r
  " Hide the menu bar.
  "set guioptions-=m
  " Hide the bottom scroll bar.
  "set guioptions-=b

endif
