-- require("usr.base")
-- require("usr.lazy")
-- require("colorscheme")
-- -- require("autocmds")
-- -- require("keymap")
-- 
--  vim.api.nvim_create_autocmd("User", {
--    pattern = "VeryLazy",
--    callback = function()
--      require("autocmds")
--      require("keymap")
--    end,
--  })
require("config.lazy")
