require("user.plugins.plugins-setup")
require("user.options")
require("user.keymaps")
require("user.colorscheme")
require("user.plugins.nvim-tree")
require("user.plugins.lualine")
require("user.plugins.comment")
require("user.plugins.treesitter")
