jobs:
  macOS:
    runs-on: macos-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install shellcheck


name: macOS

on: push
